# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import workout_pb2 as workout__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workout_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkoutServiceStub(object):
    """WorkoutService exposes CRUD operations for workout entries.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWorkout = channel.unary_unary(
                '/workout.WorkoutService/GetWorkout',
                request_serializer=workout__pb2.GetWorkoutRequest.SerializeToString,
                response_deserializer=workout__pb2.WorkoutResponse.FromString,
                _registered_method=True)
        self.ListWorkouts = channel.unary_unary(
                '/workout.WorkoutService/ListWorkouts',
                request_serializer=workout__pb2.ListWorkoutsRequest.SerializeToString,
                response_deserializer=workout__pb2.ListWorkoutsResponse.FromString,
                _registered_method=True)
        self.CreateWorkout = channel.unary_unary(
                '/workout.WorkoutService/CreateWorkout',
                request_serializer=workout__pb2.CreateWorkoutRequest.SerializeToString,
                response_deserializer=workout__pb2.WorkoutResponse.FromString,
                _registered_method=True)


class WorkoutServiceServicer(object):
    """WorkoutService exposes CRUD operations for workout entries.
    """

    def GetWorkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkouts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWorkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkoutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWorkout': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkout,
                    request_deserializer=workout__pb2.GetWorkoutRequest.FromString,
                    response_serializer=workout__pb2.WorkoutResponse.SerializeToString,
            ),
            'ListWorkouts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkouts,
                    request_deserializer=workout__pb2.ListWorkoutsRequest.FromString,
                    response_serializer=workout__pb2.ListWorkoutsResponse.SerializeToString,
            ),
            'CreateWorkout': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkout,
                    request_deserializer=workout__pb2.CreateWorkoutRequest.FromString,
                    response_serializer=workout__pb2.WorkoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workout.WorkoutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workout.WorkoutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkoutService(object):
    """WorkoutService exposes CRUD operations for workout entries.
    """

    @staticmethod
    def GetWorkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workout.WorkoutService/GetWorkout',
            workout__pb2.GetWorkoutRequest.SerializeToString,
            workout__pb2.WorkoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkouts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workout.WorkoutService/ListWorkouts',
            workout__pb2.ListWorkoutsRequest.SerializeToString,
            workout__pb2.ListWorkoutsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWorkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workout.WorkoutService/CreateWorkout',
            workout__pb2.CreateWorkoutRequest.SerializeToString,
            workout__pb2.WorkoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
