# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workout.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'workout.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rworkout.proto\x12\x07workout\"\x84\x01\n\x07Workout\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08\x64uration\x18\x04 \x01(\x05\x12\x12\n\ndifficulty\x18\x05 \x01(\t\x12\x17\n\x0f\x63\x61lories_burned\x18\x06 \x01(\x05\x12\x12\n\ncreated_at\x18\x07 \x01(\t\"\x1f\n\x11GetWorkoutRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x15\n\x13ListWorkoutsRequest\":\n\x14ListWorkoutsResponse\x12\"\n\x08workouts\x18\x01 \x03(\x0b\x32\x10.workout.Workout\"q\n\x14\x43reateWorkoutRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\x05\x12\x12\n\ndifficulty\x18\x04 \x01(\t\x12\x17\n\x0f\x63\x61lories_burned\x18\x05 \x01(\x05\"4\n\x0fWorkoutResponse\x12!\n\x07workout\x18\x01 \x01(\x0b\x32\x10.workout.Workout2\xeb\x01\n\x0eWorkoutService\x12\x42\n\nGetWorkout\x12\x1a.workout.GetWorkoutRequest\x1a\x18.workout.WorkoutResponse\x12K\n\x0cListWorkouts\x12\x1c.workout.ListWorkoutsRequest\x1a\x1d.workout.ListWorkoutsResponse\x12H\n\rCreateWorkout\x12\x1d.workout.CreateWorkoutRequest\x1a\x18.workout.WorkoutResponseB6Z4github.com/Dev66-66/LB10/go-service/internal/grpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workout_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/Dev66-66/LB10/go-service/internal/grpc/pb'
  _globals['_WORKOUT']._serialized_start=27
  _globals['_WORKOUT']._serialized_end=159
  _globals['_GETWORKOUTREQUEST']._serialized_start=161
  _globals['_GETWORKOUTREQUEST']._serialized_end=192
  _globals['_LISTWORKOUTSREQUEST']._serialized_start=194
  _globals['_LISTWORKOUTSREQUEST']._serialized_end=215
  _globals['_LISTWORKOUTSRESPONSE']._serialized_start=217
  _globals['_LISTWORKOUTSRESPONSE']._serialized_end=275
  _globals['_CREATEWORKOUTREQUEST']._serialized_start=277
  _globals['_CREATEWORKOUTREQUEST']._serialized_end=390
  _globals['_WORKOUTRESPONSE']._serialized_start=392
  _globals['_WORKOUTRESPONSE']._serialized_end=444
  _globals['_WORKOUTSERVICE']._serialized_start=447
  _globals['_WORKOUTSERVICE']._serialized_end=682
# @@protoc_insertion_point(module_scope)
