// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: workout.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workout struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Duration       int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Difficulty     string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	CaloriesBurned int32                  `protobuf:"varint,6,opt,name=calories_burned,json=caloriesBurned,proto3" json:"calories_burned,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Workout) Reset() {
	*x = Workout{}
	mi := &file_workout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workout) ProtoMessage() {}

func (x *Workout) ProtoReflect() protoreflect.Message {
	mi := &file_workout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workout.ProtoReflect.Descriptor instead.
func (*Workout) Descriptor() ([]byte, []int) {
	return file_workout_proto_rawDescGZIP(), []int{0}
}

func (x *Workout) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workout) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Workout) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Workout) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Workout) GetCaloriesBurned() int32 {
	if x != nil {
		return x.CaloriesBurned
	}
	return 0
}

func (x *Workout) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkoutRequest) Reset() {
	*x = GetWorkoutRequest{}
	mi := &file_workout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkoutRequest) ProtoMessage() {}

func (x *GetWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkoutRequest.ProtoReflect.Descriptor instead.
func (*GetWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_workout_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorkoutRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListWorkoutsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkoutsRequest) Reset() {
	*x = ListWorkoutsRequest{}
	mi := &file_workout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkoutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkoutsRequest) ProtoMessage() {}

func (x *ListWorkoutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkoutsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkoutsRequest) Descriptor() ([]byte, []int) {
	return file_workout_proto_rawDescGZIP(), []int{2}
}

type ListWorkoutsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workouts      []*Workout             `protobuf:"bytes,1,rep,name=workouts,proto3" json:"workouts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkoutsResponse) Reset() {
	*x = ListWorkoutsResponse{}
	mi := &file_workout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkoutsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkoutsResponse) ProtoMessage() {}

func (x *ListWorkoutsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkoutsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkoutsResponse) Descriptor() ([]byte, []int) {
	return file_workout_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkoutsResponse) GetWorkouts() []*Workout {
	if x != nil {
		return x.Workouts
	}
	return nil
}

type CreateWorkoutRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Duration       int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Difficulty     string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	CaloriesBurned int32                  `protobuf:"varint,5,opt,name=calories_burned,json=caloriesBurned,proto3" json:"calories_burned,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateWorkoutRequest) Reset() {
	*x = CreateWorkoutRequest{}
	mi := &file_workout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkoutRequest) ProtoMessage() {}

func (x *CreateWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkoutRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_workout_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkoutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkoutRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateWorkoutRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateWorkoutRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateWorkoutRequest) GetCaloriesBurned() int32 {
	if x != nil {
		return x.CaloriesBurned
	}
	return 0
}

type WorkoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workout       *Workout               `protobuf:"bytes,1,opt,name=workout,proto3" json:"workout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutResponse) Reset() {
	*x = WorkoutResponse{}
	mi := &file_workout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutResponse) ProtoMessage() {}

func (x *WorkoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutResponse.ProtoReflect.Descriptor instead.
func (*WorkoutResponse) Descriptor() ([]byte, []int) {
	return file_workout_proto_rawDescGZIP(), []int{5}
}

func (x *WorkoutResponse) GetWorkout() *Workout {
	if x != nil {
		return x.Workout
	}
	return nil
}

var File_workout_proto protoreflect.FileDescriptor

const file_workout_proto_rawDesc = "" +
	"\n" +
	"\rworkout.proto\x12\aworkout\"\xc5\x01\n" +
	"\aWorkout\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12'\n" +
	"\x0fcalories_burned\x18\x06 \x01(\x05R\x0ecaloriesBurned\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"#\n" +
	"\x11GetWorkoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x15\n" +
	"\x13ListWorkoutsRequest\"D\n" +
	"\x14ListWorkoutsResponse\x12,\n" +
	"\bworkouts\x18\x01 \x03(\v2\x10.workout.WorkoutR\bworkouts\"\xa3\x01\n" +
	"\x14CreateWorkoutRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12'\n" +
	"\x0fcalories_burned\x18\x05 \x01(\x05R\x0ecaloriesBurned\"=\n" +
	"\x0fWorkoutResponse\x12*\n" +
	"\aworkout\x18\x01 \x01(\v2\x10.workout.WorkoutR\aworkout2\xeb\x01\n" +
	"\x0eWorkoutService\x12B\n" +
	"\n" +
	"GetWorkout\x12\x1a.workout.GetWorkoutRequest\x1a\x18.workout.WorkoutResponse\x12K\n" +
	"\fListWorkouts\x12\x1c.workout.ListWorkoutsRequest\x1a\x1d.workout.ListWorkoutsResponse\x12H\n" +
	"\rCreateWorkout\x12\x1d.workout.CreateWorkoutRequest\x1a\x18.workout.WorkoutResponseB6Z4github.com/Dev66-66/LB10/go-service/internal/grpc/pbb\x06proto3"

var (
	file_workout_proto_rawDescOnce sync.Once
	file_workout_proto_rawDescData []byte
)

func file_workout_proto_rawDescGZIP() []byte {
	file_workout_proto_rawDescOnce.Do(func() {
		file_workout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_proto_rawDesc), len(file_workout_proto_rawDesc)))
	})
	return file_workout_proto_rawDescData
}

var file_workout_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_workout_proto_goTypes = []any{
	(*Workout)(nil),              // 0: workout.Workout
	(*GetWorkoutRequest)(nil),    // 1: workout.GetWorkoutRequest
	(*ListWorkoutsRequest)(nil),  // 2: workout.ListWorkoutsRequest
	(*ListWorkoutsResponse)(nil), // 3: workout.ListWorkoutsResponse
	(*CreateWorkoutRequest)(nil), // 4: workout.CreateWorkoutRequest
	(*WorkoutResponse)(nil),      // 5: workout.WorkoutResponse
}
var file_workout_proto_depIdxs = []int32{
	0, // 0: workout.ListWorkoutsResponse.workouts:type_name -> workout.Workout
	0, // 1: workout.WorkoutResponse.workout:type_name -> workout.Workout
	1, // 2: workout.WorkoutService.GetWorkout:input_type -> workout.GetWorkoutRequest
	2, // 3: workout.WorkoutService.ListWorkouts:input_type -> workout.ListWorkoutsRequest
	4, // 4: workout.WorkoutService.CreateWorkout:input_type -> workout.CreateWorkoutRequest
	5, // 5: workout.WorkoutService.GetWorkout:output_type -> workout.WorkoutResponse
	3, // 6: workout.WorkoutService.ListWorkouts:output_type -> workout.ListWorkoutsResponse
	5, // 7: workout.WorkoutService.CreateWorkout:output_type -> workout.WorkoutResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workout_proto_init() }
func file_workout_proto_init() {
	if File_workout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_proto_rawDesc), len(file_workout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workout_proto_goTypes,
		DependencyIndexes: file_workout_proto_depIdxs,
		MessageInfos:      file_workout_proto_msgTypes,
	}.Build()
	File_workout_proto = out.File
	file_workout_proto_goTypes = nil
	file_workout_proto_depIdxs = nil
}
